version: '3.8'

services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   command: ["npm", "run", "start:dev"]
  #   environment:
  #     NODE_ENV: "development"
  #     EMAIL_USER: "anyuser"
  #     EMAIL_PASS: "anypass"
  #     MONGO_URI: "mongodb://mongodb:27017/dbname"
  #   depends_on:
  #     - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    restart: always

volumes:
  mongodb-volume:
